### ISSUE TITLE
Server calling for client class

### ISSUE THREAD

**Issue by Milii20** [MC-U-Team/HyCraftHDs-WTF-Ic2-Addon#1]
Greetings, i installed the mod on my server, and when i placed and right clicked on the transformer MFSU, server crashed with the following crash log

https://pastebin.com/xBsygJ9k

(sorry for the empty post, i misspressed enter when creating the issue)

**Comment by HyCraftHD** [comment]
I need a crashreport to fix this

**Comment by Milii20** [comment]
my bad, i just added a missing text to the issue

**Comment by Milii20** [comment]
my guess is that
@Override
	public void addInformation(ItemStack stack, List<String> tooltip, ITooltipFlag advanced) {
	
is sideonly client on the superclass TileEntityEnergyStorageBase , but not on the childclass TileEntityEnergyStorageConvertableMFSU?
since is the only class that overrides anything with ITooltipFlag

**Comment by HyCraftHD** [comment]
Thanks for the report.
I'll have a look into it soon. One question: How can I reproduce this crash?
~HyCraftHD

**Comment by Milii20** [comment]
no problem!, easy, just install a server with forge 2806, ic2 and wtf ic2 addon, (probably hwyla and the one probe too), join the server, set yourself into creative, place a transformer mfsu, and right click it, client will disconect, and server will crash
