### ISSUE TITLE
Sudden collapse

### ISSUE THREAD

**Issue by skyerpe** [MC-U-Team/HyCraftHDs-WTF-Ic2-Addon#3]
It is said that the use of electricity storage box and molecular converter during operation will cause the server card machine and the players to drop off the line collectively!

**Comment by HyCraftHD** [comment]
Please specify that. What is the actual issue?

**Comment by skyerpe** [comment]
> Please specify that. What is the actual issue?

i'll upgrade hardware of the server latter，if it happened again. i'll reply you as soon as posssible

**Comment by HyCraftHD** [comment]
Seems to be fixed. Close for now
